theme = "ashen"

[editor]
line-number = "relative"
mouse = false
clipboard-provider = "wayland"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
skip-levels = 0

[keys.normal]
"ret" = ["open_below", "normal_mode"]
C-o = ":config-open"
Z = { Z = ":write-quit" }
E = { E = ":quit!" }
A-d = "delete_selection" # Delete slection and yank it.
d = "delete_selection_noyank" # Delete selection and don't yank it.
A-c = "change_selection" # Delete selection, yank it, and enter Insert Mode.
c = "change_selection_noyank" # Delete selection, don't yank, and enter Insert Mode.
