#!/bin/sh

case "$(file -Lb --mime-type -- "$1")" in
  image/*)
    chafa -f sixel -s "$2x$3" --animate off --polite on -t 1 --bg black "$1"
    ;;
  text/*)
    cat "$1"
    ;;
  application/vnd.rar)
    unrar lb "$1"
    ;;
  application/x-7z-compressed)
    7z l "$1"
    ;;
  application/zip)
    unzip -l "$1" | grep 'Length' -A100
    ;;
esac
