colorscheme ef-dark
add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ wrap -word -indent
add-highlighter global/ show-whitespaces -lf "" -spc " " -tab "·"
set-option global ui_options terminal_assistant=none
set-option global indentwidth 2
set-option global tabstop 2

# except for Makefile
hook global WinSetOption filetype=(?!makefile).* %{
	map global normal '<gt>' 'I<tab><esc>'
}
