source ~/.config/kak/theme.ln
add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ wrap -word -indent
add-highlighter global/ show-whitespaces -lf "" -spc " "
set-option global ui_options terminal_assistant=none
set-option global indentwidth 2
set-option global tabstop 4
