# -*- conf -*-

[main]
font = Monospace:size=12
pad = 0x0
bold-text-in-bright = yes
selection-target = primary

[environment]
name = Jack

[security]
osc52 = enabled

[bell]
system = no
urgent = yes
visual = no

[desktop-notifications]
# to be configured...

[regex:?]
# to be configured...

[cursor]
style = Block
unfocused-style = hollow
blink = Yes

[mouse]
hide-when-typing = Yes
alternate-scroll-mode = yes

[csd]
preferred = server

[key-bindings]
scrollback-up-page = Shift+Page_Up Shift+KP_Page_Up
scrollback-down-page = Shift+Page_Down Shift+KP_Page_Down
scrollback-up-line = Shift+Up
scrollback-down-line = Shift+Down
scrollback-home = Shift+Home
scrollback-end = Shift+End
clipboard-copy = Control+y XF86Copy
clipboard-paste = Control+p XF86Paste 
primary-paste = Shift+Insert
search-start = Control+Shift+r
font-increase = Control+plus Control+equal Control+KP_Add
font-decrease = Control+minus Control+KP_Subtract
font-reset = Control+0 Control+KP_0
spawn-terminal = Control+Shift+n
show-urls-launch = Control+Shift+o
show-urls-copy = Control+Shift+y
prompt-prev = Control+Shift+z
prompt-next = Control+Shift+x
unicode-input = Control+Shift+u
color-theme-toggle = Control+t

[search-bindings]

[url-bindings]

[text-bindings]

[mouse-bindings]
select-extend = none
clipboard-paste = BTN_RIGHT
