#--- Settings ---#
source "%val{config}/theme.ln"
source "%val{config}/plugins/lsp.kak"
source "%val{config}/plugins/git-branch.kak"

add-highlighter global/ number-lines -relative -hlcursor 
add-highlighter global/ wrap -word -indent -marker "↳ "
add-highlighter global/ show-matching -previous
set-option global ui_options terminal_assistant=none
set-option global indentwidth 2
set-option global tabstop 4
set-option global formatcmd 'fmt -w 65'
set-option global autowrap_column 65
set-option -add global modelinefmt '%sh{ printf " (%s)"  $(printf %s\\n $kak_buflist | wc -w) }'  
require-module wayland
set-option global termcmd 'termcmd.sh sh -c'
set-option global scrolloff 3,0

#--- Modes ---#
declare-user-mode surround

#--- Keybindings ---#
map global insert <tab> '  '
map global normal <ret> '<a-o>j'

map global normal = ':format-selections<ret>'
# map global normal X 'x'
# map global normal x 'xH'
map global normal <c-a> ': inc %val{count} +<ret>' -docstring 'Increment Number'
map global normal <c-x> ': inc %val{count} -<ret>' -docstring 'Decrement Number'
map global normal <c-m> ':enter-user-mode surround <ret>' -docstring 'Surround Selection'

map global user w ':w <ret>' -docstring 'Write'
map global user W ':wq <ret>' -docstring 'Write & Quit'
map global user q ':q <ret>' -docstring 'Quit'
map global user Q ':q! <ret>' -docstring 'Force Quit'
map global user a '*%s<ret>' -docstring 'Select All'
map global user c ':e ~/.config/kak/kakrc <ret>' -docstring 'Edit Config'
map global user y '<a-|> wl-copy <ret>' -docstring 'Copy to Clipboard'
map global user p '<|> wl-paste <ret>' -docstring 'Paste From Clipboard'
map global user n ':new <ret>' -docstring 'New Window'
map global user f ':find ' -docstring 'Find'
map global user u ':ui <ret>' -docstring 'UI'

map global surround b '\i[<esc>\a]<esc><a-i>r' -docstring 'Bracket'
map global surround [ '\i[<esc>\a]<esc><a-i>r' -docstring 'Bracket'
map global surround ] '\i[<esc>\a]<esc><a-i>r' -docstring 'Bracket'

map global surround c '\i{<esc>\a}<esc><a-i>B' -docstring 'Curly Brace'
map global surround { '\i{<esc>\a}<esc><a-i>B' -docstring 'Curly Brace'
map global surround } '\i{<esc>\a}<esc><a-i>B' -docstring 'Curly Brace'

map global surround p '\i(<esc>\a)<esc><a-i>b' -docstring 'Parenthesis'
map global surround ( '\i(<esc>\a)<esc><a-i>b' -docstring 'Parenthesis'
map global surround ) '\i(<esc>\a)<esc><a-i>b' -docstring 'Parenthesis'

map global surround q "\i'<esc>\a'<esc><a-i>q" -docstring 'Quote'
map global surround "'" "\i'<esc>\a'<esc><a-i>q" -docstring 'Quote'

map global surround Q '\i"<esc>\a"<esc><a-i>Q' -docstring 'Double Quote'
map global surround '"' '\i"<esc>\a"<esc><a-i>Q' -docstring 'Double Quote'

map global surround a "\i<lt><esc>\a<gt><esc><a-i><lt>" -docstring 'Angle'
map global surround < "\i<lt><esc>\a<gt><esc><a-i><lt>" -docstring 'Angle'
map global surround > "\i<lt><esc>\a<gt><esc><a-i><lt>" -docstring 'Angle'

map global surround u "\i_<esc>\a_<esc>" -docstring 'Underline'
map global surround _ "\i_<esc>\a_<esc>" -docstring 'Underline'

map global surround * "\i*<esc>\a*<esc>" -docstring 'Asterisks'

#--- Commands ---#
define-command find -docstring "Find Files" -params 1 %{ edit %arg{1} }
complete-command find shell-script-candidates %{ find . -type f }

define-command -docstring "Increment/Decrement Numbers" -hidden -params 2 inc %{ try %{
    evaluate-commands %sh{
        [ "$1" = 0 ] && count=1 || count="$1"
        printf '%s%s' 'exec h"_/\d<ret><a-i>na' "$2($count)<esc>|{<space>cat<semicolon>echo<semicolon>}|bc<ret>"
    }} catch %{
    execute-keys l
}}

#--- Hooks ---#
# Autowrap
hook global WinSetOption filetype=(asciidoc|markdown) %{
  set-option window autowrap_column 65
  autowrap-enable
}

# Tab Complete
hook global InsertCompletionShow .* %{
  map window insert <tab> <c-n>
  map window insert <s-tab> <c-p>
}

hook global InsertCompletionHide .* %{
  unmap window insert <tab> <c-n>
  unmap window insert <s-tab> <c-p>
}

# Detect lf files as shell scripts
hook global BufCreate .*/lf/.* %{ set-option buffer filetype sh }

# Auto-Pair: Generic
# hook global BufSetOption filetype=.+ %{
#   hook buffer InsertChar '\[' %{ execute-keys ']<left>' }
#   hook buffer InsertChar '\{' %[ execute-keys '}<left>' ]
#   hook buffer InsertChar '<' %{ execute-keys '<gt><left>' }
#   hook buffer InsertChar '\(' %{ execute-keys ')<left>' }
# }

# Auto-Pair: Specific
hook global BufSetOption filetype=(markdown|asciidoc) %{
  hook buffer InsertChar "\*" %{ execute-keys "*<left>" }
  hook buffer InsertChar "_" %{ execute-keys "_<left>" }
  hook buffer InsertChar "`" %{ execute-keys "`<left>" }
}

# ui
hook global WinCreate .* %{
    ui-cursorline-toggle
    ui-matching-toggle
    ui-search-toggle
}
