### General ###
  source "%val{config}/theme.ln"
  add-highlighter global/ number-lines -relative -hlcursor
  add-highlighter global/ wrap -word -indent -marker "↳ "
  add-highlighter global/ show-matching -previous
  set-option global ui_options terminal_assistant=none
  set-option global indentwidth 2
  set-option global tabstop 4
  set-option global autowrap_column 50

### Kebindings ###
  map global normal <ret> '<a-o>j'
  map global insert <tab> '  '
  map global normal = '|fmt -w $kak_opt_autowrap_column<ret>'

### User Mode ###
# Quick write and quit shortcuts
  map global user <w> ':w <ret>' -docstring 'write'
  map global user <W> ':wq <ret>' -docstring 'write & quit'
  map global user <q> ':q <ret>' -docstring 'quit'
  map global user <Q> ':q! <ret>' -docstring 'force quit'
  map global user a '*%s<ret>' -docstring 'select all'
# Quickly edit config file
  map global user <c> ':e ~/.config/kak/kakrc <ret>' -docstring 'edit config'
# Yank and Paste from wl-clipboar
  map global user <y> '<a-|> wl-copy <ret>' -docstring 'copy to clipboard'
  map global user <p> '<|> wl-paste <ret>' -docstring 'paste from clipboard'

### Kak-LSP ###
  eval %sh{kak-lsp}
  lsp-enable

  set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"

  map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'
  map global goto d <esc>:lsp-definition<ret> -docstring 'LSP definition'
  map global goto r <esc>:lsp-references<ret> -docstring 'LSP references'
  map global goto y <esc>:lsp-type-definition<ret> -docstring 'LSP type definition'
  map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
  map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
  map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
  map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
  map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
  map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP errors and warnings'
  map global object D '<a-semicolon>lsp-diagnostic-object error<ret>' -docstring 'LSP errors'

