#!/usr/bin/env sh

FIFO="$XDG_RUNTIME_DIR/sandbar"
[ -e "$FIFO" ] && rm -f "$FIFO"
mkfifo "$FIFO"

while cat "$FIFO"; do :; done | sandbar \
	-font "CozetteVector:size=18" \
	-active-fg-color "#00ff66" \
	-active-bg-color "#000000" \
	-inactive-fg-color "#b2b2b2" \
	-inactive-bg-color "#000000" \
	-urgent-fg-color "#000000" \
	-urgent-bg-color "#cc241d" \
	-title-fg-color "#000000" \
	-title-bg-color "#00ff66" \
	-hide-vacant-tags
