#!/bin/sh

### Bindings ###
  # Start Foot
  riverctl map normal Super T spawn foot

  # Close the focused view
  riverctl map normal Super Q close

  # Exit river
  riverctl map normal Super+Shift Q exit

  # Focus the next/previous view in the layout stack
  riverctl map normal Super J focus-view next
  riverctl map normal Super K focus-view previous

  # Swap the focused view with the next/previous view in the layout stack
  riverctl map normal Super+Shift J swap next
  riverctl map normal Super+Shift K swap previous

  # Focus the next/previous output
  riverctl map normal Super Period focus-output next
  riverctl map normal Super Comma focus-output previous

  # Send the focused view to the next/previous output
  riverctl map normal Super+Shift Period send-to-output next
  riverctl map normal Super+Shift Comma send-to-output previous

  # Bump the focused view to the top of the layout stack
  riverctl map normal Super Return zoom

  # Decrease/increase the main ratio of rivertile(1)
  riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
  riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

  # Increment/decrement the main count of rivertile(1)
  riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
  riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

  # Move views
  riverctl map normal Super+Alt H move left 100
  riverctl map normal Super+Alt J move down 100
  riverctl map normal Super+Alt K move up 100
  riverctl map normal Super+Alt L move right 100

  # Snap views to screen edges
  riverctl map normal Super+Alt+Control H snap left
  riverctl map normal Super+Alt+Control J snap down
  riverctl map normal Super+Alt+Control K snap up
  riverctl map normal Super+Alt+Control L snap right

  # Resize views
  riverctl map normal Super+Alt+Shift H resize horizontal -100
  riverctl map normal Super+Alt+Shift J resize vertical 100
  riverctl map normal Super+Alt+Shift K resize vertical -100
  riverctl map normal Super+Alt+Shift L resize horizontal 100

  # Mouse Button to move views
  riverctl map-pointer normal Super BTN_LEFT move-view

  # Mouse Button to resize views
  riverctl map-pointer normal Super BTN_RIGHT resize-view

  # Mouse Button to toggle float
  riverctl map-pointer normal Super BTN_MIDDLE toggle-float

  for i in $(seq 1 9)
  do
      tags=$((1 << ($i - 1)))

      # Super+[1-9] to focus tag [0-8]
      riverctl map normal Super $i set-focused-tags $tags

      # Super+Shift+[1-9] to tag focused view with tag [0-8]
      riverctl map normal Super+Shift $i set-view-tags $tags

      # Super+Control+[1-9] to toggle focus of tag [0-8]
      riverctl map normal Super+Control $i toggle-focused-tags $tags

      # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
      riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
  done

  # Super+0 to focus all tags
  # Super+Shift+0 to tag focused view with all tags
  all_tags=$(((1 << 32) - 1))
  riverctl map normal Super 0 set-focused-tags $all_tags
  riverctl map normal Super+Shift 0 set-view-tags $all_tags

  # Toggle float
  riverctl map normal Super+Shift Space toggle-float

  # Toggle fullscreen
  riverctl map normal Super F toggle-fullscreen

  # Change layout orientation
  riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
  riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
  riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
  riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

  # Enter passthrough mode
  riverctl map normal Super F11 enter-mode passthrough

  # Return to normal mode
  riverctl map passthrough Super F11 enter-mode normal

  # Various media key mapping examples for both normal and locked mode which do
  # not have a modifier
  for mode in normal locked
  do
      # Eject the optical drive (well if you still have one that is)
      riverctl map $mode None XF86Eject spawn 'eject -T'

      # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
      riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
      riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
      riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

      # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
      riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
      riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
      riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
      riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

      # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
      riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
      riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
  done

  # Spawn LF file manager in Foot
  riverctl map normal Super E spawn "foot lf"

  # Spawn Firefox
  riverctl map normal Super B spawn "firefox"

  # Power menu
  riverctl map normal Super+Control P spawn "power-menu.sh"

  # Menu
  riverctl map normal Super space spawn "wmenu.sh"
  
### Settings ###
  # Set background and border color
  riverctl border-color-focused 0x00ff66
  riverctl border-color-unfocused 0x586e75

  # Set keyboard repeat rate
  riverctl set-repeat 80 200

  # Make all views with an app-id that starts with "float" and title "foo" start floating.
  riverctl rule-add -app-id 'float*' -title 'foo' float

  # Make all views with app-id "bar" and any title use client-side decorations
  riverctl rule-add -app-id "bar" csd

  # Set the default layout generator to be rivertile and start it.
  # River will send the process group of the init executable SIGTERM on exit.
  riverctl default-layout rivertile
  rivertile -view-padding 6 -outer-padding 6 &

  # Declare a passthrough mode. This mode has only a single mapping to return to
  # normal mode. This makes it useful for testing a nested wayland compositor
  riverctl declare-mode passthrough

  # Configure trackpoint acceleration
  riverctl input pointer-2-10-TPPS/2_IBM_TrackPoint accel-profile flat
  riverctl input pointer-2-10-TPPS/2_IBM_TrackPoint pointer-accel 0.3

  # Keyboard Layouts
  riverctl keyboard-layout -options "grp:ctrl_space_toggle" "us,ir"

### Autostart ###
  riverctl spawn pipewire
  riverctl spawn "wl-paste --watch cliphist store"
  riverctl spawn "swaybg -i ~/pic/wallpaper.ln"
  riverctl spawn "$HOME/.config/river/status"
  riverctl spawn "$HOME/.config/river/bar"

  # Get monitor name, highest resolution, and refresh rate.
  MONITOR=$(wlr-randr | awk 'NR==1{print $1; exit}')
  RES=$(wlr-randr | grep px | awk 'NR==1{ print $1 }')
  REF=$(wlr-randr --json | grep refresh | awk '{ print $2 }' | sed 's/,//g' | sort -n | tail -n 1)
  # Setup resolution and refresh rate
  riverctl spawn "wlr-randr --output $MONITOR --mode ${RES}@${REF}"
