#!/bin/sh

#--- Variables ---#
  mod=Super

# Get monitor name, highest resolution, and refresh rate.
  MONITOR=$(wlr-randr | awk 'NR==1{print $1; exit}')
  RES=$(wlr-randr | awk '/px,/ {print $1}')
  REF=$(wlr-randr | awk '/px,/ {print $3}' | sort -n | tail -n 1)

#--- Bindings ---#
# Start Foot
  riverctl map normal $mod T spawn foot

# Close the focused view
  riverctl map normal $mod Q close

# Exit river
  riverctl map normal $mod+Shift Q exit

# Focus the next/previous view in the layout stack
  riverctl map normal $mod J focus-view next
  riverctl map normal $mod K focus-view previous

# Swap the focused view with the next/previous view in the layout stack
  riverctl map normal $mod+Shift J swap next
  riverctl map normal $mod+Shift K swap previous

# Focus the next/previous output
  riverctl map normal $mod Period focus-output next
  riverctl map normal $mod Comma focus-output previous

# Send the focused view to the next/previous output
  riverctl map normal $mod+Shift Period send-to-output next
  riverctl map normal $mod+Shift Comma send-to-output previous

# Bump the focused view to the top of the layout stack
  riverctl map normal $mod Return zoom

# Decrease/increase the main ratio of rivertile(1)
  riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
  riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Increment/decrement the main count of rivertile(1)
  riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
  riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Move views
  riverctl map normal $mod+Alt H move left 100
  riverctl map normal $mod+Alt J move down 100
  riverctl map normal $mod+Alt K move up 100
  riverctl map normal $mod+Alt L move right 100

# Snap views to screen edges
  riverctl map normal $mod+Alt+Control H snap left
  riverctl map normal $mod+Alt+Control J snap down
  riverctl map normal $mod+Alt+Control K snap up
  riverctl map normal $mod+Alt+Control L snap right

# Resize views
  riverctl map normal $mod+Alt+Shift H resize horizontal -100
  riverctl map normal $mod+Alt+Shift J resize vertical 100
  riverctl map normal $mod+Alt+Shift K resize vertical -100
  riverctl map normal $mod+Alt+Shift L resize horizontal 100

# Enable trackpad tap to click
  riverctl input pointer* tap enabled

# Mouse Button to move views
  riverctl map-pointer normal $mod BTN_LEFT move-view

# Mouse Button to resize views
  riverctl map-pointer normal $mod BTN_RIGHT resize-view

# Mouse Button to toggle float
  riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

  for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))

    # $mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tags

    # $mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # $mod+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # $mod+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
  done

# mod+0 to focus all tags
# mod+Shift+0 to tag focused view with all tags
  all_tags=$(((1 << 32) - 1))
  riverctl map normal $mod 0 set-focused-tags $all_tags
  riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Toggle float
  riverctl map normal $mod+Shift Space toggle-float

# Toggle fullscreen
  riverctl map normal $mod F toggle-fullscreen

# Change layout orientation
  riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
  riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
  riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
  riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

# Enter passthrough mode
  riverctl map normal $mod F11 enter-mode passthrough

# Return to normal mode
  riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do # not have a modifier
  for mode in normal locked; do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
  done

# Spawn LF file manager in Foot
  riverctl map normal $mod E spawn "termcmd.sh lf"

# Spawn default browser
  riverctl map normal $mod B spawn "$BROWSER"

# Power menu
  riverctl map normal $mod+Control P spawn "power-menu.sh"

# Menu
  riverctl map normal $mod space spawn "wmenu.sh"
  
#--- Settings ---#
# Set background and border color
  riverctl border-color-focused 0x00ff66
  riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
  riverctl set-repeat 80 200

# Make all views with an app-id that starts with "float" and title "foo" start floating.
  riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
  riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
  riverctl default-layout rivertile
  rivertile -view-padding 6 -outer-padding 6 &

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
  riverctl declare-mode passthrough

# Configure trackpoint acceleration
  riverctl input pointer-2-10-TPPS/2_IBM_TrackPoint accel-profile flat
  riverctl input pointer-2-10-TPPS/2_IBM_TrackPoint pointer-accel 0.3

# Keyboard Layouts
  riverctl keyboard-layout -options "grp:ctrl_space_toggle" "us,ir"

#--- Autostart ---#
  riverctl spawn "pipewire"
  riverctl spawn "pipewire-pulse"
  riverctl spawn "wireplumber"
  riverctl spawn "mako"
  riverctl spawn "wl-paste --watch cliphist store"
  riverctl spawn "swaybg -i ~/pic/wallpaper.ln"

# Setup resolution and refresh rate
  riverctl spawn "wlr-randr --output $MONITOR --mode ${RES}@${REF}"
