# Ayu Dark Tinted
[colors-dark]
cursor = 000000 ff8f40
foreground = e6e1cf
background = 0b0e14
regular0 = 0b0e14 # black
regular1 = f07178 # red
regular2 = aad94c # green
regular3 = ffb454 # yellow
regular4 = 59c2ff # blue
regular5 = d2a6ff # magenta
regular6 = 95e6cb # cyan
regular7 = e6e1cf # white
bright0 = 3e4b59 # bright black
bright1 = f07178 # bright red
bright2 = aad94c # bright green
bright3 = ffb454 # bright yellow
bright4 = 59c2ff # bright blue
bright5 = d2a6ff # bright magenta
bright6 = 95e6cb # bright cyan
bright7 = f2f0e7 # bright white
