# Ef-Deuteranopia-Dark
[colors-dark]
cursor = 000a1f b379bf
foreground = ddddee
background = 000a1f

regular0 = 000000 # Black
regular1 = cf8660 # Red
regular2 = 3faa26 # Green
regular3 = aa9f32 # Yellow
regular4 = 3f90f0 # Blue
regular5 = b379bf # Magenta
regular6 = 5faaef # Cyan
regular7 = ffffff # White

bright0 = 262626 # Bright Black
bright1 = cf7a7a # Bright Red
bright2 = 3fa672 # Bright Green
bright3 = bfaf7a # Bright Yellow
bright4 = 009fff # Bright Blue
bright5 = 9f95ff # Bright Magenta
bright6 = 0db0ff # Bright Cyan 
bright7 = ffffff # Bright White

dim0 = 000000 # Dim Black 
dim1 = e47360 # Dim Red
dim2 = 7aad0f # Dim Green 
dim3 = cfaf00 # Dim Yellow 
dim4 = 6a9fff # Dim Blue 
dim5 = af80ea # Dim Magenta 
dim6 = 7fafff # Dim Cyan 
dim7 = d9d9d9 # Dim White


# Ef-Deuteranopia-Light
[colors-light]
cursor = f5f5ff ba35af
foreground = 1a1a2f
background = f5f5ff

regular0 = 000000 # Black
regular1 = d3303a # Red
regular2 = 217a3c # Green
regular3 = 805d00 # Yellow
regular4 = 375cd8 # Blue
regular5 = ba35af # Magenta
regular6 = 1f6fbf # Cyan
regular7 = ffffff # White

bright0 = 262626 # Bright Black
bright1 = d50f7f # Bright Red
bright2 = 008058 # Bright Green
bright3 = 765040 # Bright Yellow
bright4 = 065fff # Bright Blue
bright5 = 6052cf # Bright Magenta
bright6 = 1477b2 # Bright Cyan 
bright7 = ffffff # Bright White

dim0 = 000000 # Dim Black 
dim1 = e00033 # Dim Red
dim2 = 4a7d00 # Dim Green 
dim3 = 965000 # Dim Yellow 
dim4 = 4250ef # Dim Blue 
dim5 = cf25aa # Dim Magenta 
dim6 = 3f6faf # Dim Cyan 
dim7 = d9d9d9 # Dim White

