# Ef-Day
[colors-dark]
cursor = f5f5ff ba35af
foreground = 1a1a2f
background = fff5ea

regular0 = 000000 # Black
regular1 = ba2d2f # Red
regular2 = 007a0a # Green
regular3 = a45a22 # Yellow
regular4 = 375cc6 # Blue
regular5 = ca3e54 # Magenta
regular6 = 3f60af # Cyan
regular7 = ffffff # White

bright0 = 262626 # Bright Black
bright1 = cf2f4f # Bright Red
bright2 = 0f7f5f # Bright Green
bright3 = aa4f30 # Bright Yellow
bright4 = 265fbf # Bright Blue
bright5 = 8448aa # Bright Magenta
bright6 = 0f7b8f # Bright Cyan 
bright7 = ffffff # Bright White

dim0 = 000000 # Dim Black 
dim1 = ce3f00 # Dim Red
dim2 = 5f7200 # Dim Green 
dim3 = b75515 # Dim Yellow 
dim4 = 5f5fdf # Dim Blue 
dim5 = cb2f80 # Dim Magenta 
dim6 = 3f6faf # Dim Cyan 
dim7 = d9d9d9 # Dim White


# Ef-Night
[colors-light]
cursor = d570af afbcbf
foreground = afbcbf
background = 000e17

regular0 = 000000 # Black
regular1 = ef656a # Red
regular2 = 1fa526 # Green
regular3 = c48502 # Yellow
regular4 = 379cf6 # Blue
regular5 = d570af # Magenta
regular6 = 4fb0cf # Cyan
regular7 = ffffff # White

bright0 = 262626 # Bright Black
bright1 = ef798f # Bright Red
bright2 = 00a972 # Bright Green
bright3 = df8f6f # Bright Yellow
bright4 = 029fff # Bright Blue
bright5 = af8aff # Bright Magenta
bright6 = 3dc0b0 # Bright Cyan 
bright7 = ffffff # Bright White

dim0 = 000000 # Dim Black 
dim1 = f47360 # Dim Red
dim2 = 50a22f # Dim Green 
dim3 = e6832f # Dim Yellow 
dim4 = 6a88ff # Dim Blue 
dim5 = e580ea # Dim Magenta 
dim6 = 6fafff # Dim Cyan 
dim7 = d9d9d9 # Dim White


